import { Expense } from "./types";

export const SEED_EXPENSES: Expense[] = [
  { id: "1", date: "May 22 2026", description: "Kitchen", amount: 17.17, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "2", date: "May 23 2026", description: "Wimal Authentic Thai", amount: 22.02, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "3", date: "May 23 2026", description: "Atl Boarshead Cake", amount: 5.67, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "4", date: "May 24 2026", description: "Wabi Sabi Sushi", amount: 85.51, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "5", date: "May 24 2026", description: "Rack Room Shoes", amount: 161.60, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "6", date: "May 24 2026", description: "Uber", amount: 64.46, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "7", date: "May 25 2026", description: "Mopop", amount: 115.45, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "8", date: "May 25 2026", description: "The Coupe & Flute", amount: 169.47, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "9", date: "May 25 2026", description: "Lottie's Lounge", amount: 29.83, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "10", date: "May 25 2026", description: "Ixl Family Subscript", amount: 10.46, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "11", date: "May 25 2026", description: "Perihelion Brewery", amount: 83.04, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "12", date: "May 26 2026", description: "Seattle Monorail", amount: 4.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "13", date: "May 26 2026", description: "Orca (transit)", amount: 3.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "14", date: "May 26 2026", description: "Groupon", amount: 65.60, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "15", date: "May 27 2026", description: "Discover Your Nort", amount: 5.55, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "16", date: "May 28 2026", description: "Amaros Table Cas", amount: 150.19, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "17", date: "May 28 2026", description: "PCC Community Markets", amount: 115.01, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "18", date: "May 29 2026", description: "Olympia Coffee", amount: 4.67, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "19", date: "May 29 2026", description: "Sleeper Coffee", amount: 18.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "20", date: "May 29 2026", description: "Fort George Brewery", amount: 162.90, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "21", date: "May 29 2026", description: "The Berry Patch", amount: 81.78, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "22", date: "May 29 2026", description: "Astoria Brewing Co", amount: 27.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "23", date: "May 30 2026", description: "Columbia City Bake", amount: 1.93, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "24", date: "May 30 2026", description: "Broder Strand", amount: 85.50, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "25", date: "May 30 2026", description: "Mox Boarding House", amount: 18.13, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "26", date: "May 30 2026", description: "Graduate Seattle", amount: 54.39, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "27", date: "May 30 2026", description: "Orca (transit)", amount: 3.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "28", date: "May 31 2026", description: "Momiji", amount: 178.72, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "29", date: "May 31 2026", description: "Vivi", amount: 130.17, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "30", date: "May 31 2026", description: "Lyft", amount: 33.99, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "31", date: "May 31 2026", description: "Orca (transit)", amount: 3.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "32", date: "May 31 2026", description: "Montlakebike.com", amount: 139.29, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "33", date: "May 31 2026", description: "Analog Coffee", amount: 10.60, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "34", date: "May 31 2026", description: "Cellars", amount: 71.47, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "35", date: "May 31 2026", description: "Linda's Tavern", amount: 214.87, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "36", date: "May 31 2026", description: "Mars", amount: 119.77, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "37", date: "May 31 2026", description: "Rondo Japanese Kitchen", amount: 86.17, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "38", date: "May 31 2026", description: "Lsu Corvus and Company", amount: 60.20, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "39", date: "May 31 2026", description: "Kobo", amount: 19.90, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "40", date: "Jun 1 2026", description: "Hudson News", amount: 5.95, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "41", date: "Jun 1 2026", description: "Poke to the Max", amount: 39.72, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "42", date: "Jun 1 2026", description: "Orca (transit)", amount: 1.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "43", date: "Jun 1 2026", description: "Rachel's Ginger Beer", amount: 21.60, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "44", date: "Jun 1 2026", description: "Muto", amount: 32.59, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "45", date: "Jun 1 2026", description: "Oxbow", amount: 61.18, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "46", date: "Jun 1 2026", description: "Orca (transit)", amount: 1.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "47", date: "Jun 1 2026", description: "Empire Roasters", amount: 11.75, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "48", date: "Jun 1 2026", description: "Orca (transit)", amount: 3.00, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "49", date: "Jun 1 2026", description: "Uber", amount: 27.50, split: ["Phil"], receiptUrl: null, notes: "" },
  { id: "50", date: "Jun 1 2026", description: "PCC Community Markets", amount: 8.51, split: ["Phil"], receiptUrl: null, notes: "" },
];
